include:
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: torabo_tsuki_lp_left_central
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    artifact-name: torabo_tsuki_lp_right_peripheral
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    artifact-name: torabo_tsuki_lp_left_peripheral
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: torabo_tsuki_lp_right_central
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    snippet: split-trackball
    artifact-name: torabo_tsuki_lp_double_ball_left_peripheral
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    snippet: split-trackball-listner
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: torabo_tsuki_lp_double_ball_right_central
  - board: bmp_boost
    shield: settings_reset