services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-codebox-for-trabo-tsuki-lp
    working_dir: /workspace
    volumes:
      - ./:/workspace
      # - ./api:/workspace/api
      # - ./db:/workspace/db
      # - ./frontend:/workspace/frontend
    ports:
      - "5431:5431"       # frontend (Vite dev server)
      - "3000:3000"       # api (Go APIなど)
    tty: true
